apiVersion: tekton.dev/v1beta1

kind: Task

metadata:
  name: scan-fs

spec:
  description: This task is for scanning the file system.

  workspaces:
    - name: source
      description: A workspace that contains fetched filesystem.
  params:
    - name: fs-scan
      type: string
      description: Absolute path of the filesystem to be scanned.
      default: ""

  steps:
    - name: scan-fs-step
      image: aquasec/trivy:0.16.0
      workingDir: $(workspaces.source.path)
      script:  |
        
        pip freeze > requirements.txt
        pipenv lock
        trivy fs .
           

        
