apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: scan-pipeline-fs
spec:
  params:
    - name: fs-scan
  workspaces:
    - name: input
      
  tasks:
      
  - name: scan-fs
    
    taskRef:
      name: scan-fs
    workspaces:
      - name: input
        workspace: input
    params:
      - name: fs-scan
        value: $(params.fs-scan)
