apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: scan-pipelinerun-fs
spec:
  pipelineRef:
    name: scan-pipeline-fs
  workspaces:
    - name: workspace
      persistentvolumeclaim:
        claimName: trivy-pvc
  
  params:
  
  - name: fs-scan
    value: ""  
  
