apiVersion: tekton.dev/v1beta1

kind: Task

metadata:
  name: scan-fs

spec:
  description: This task is for scanning the file system.
  
  params:
    - name: fs-scan
      type: string
      description: Absolute path of the filesystem to be scanned.
      default: ""

  workspaces:
    inputs:
      - name: fs-ws
        description: Workspace for storing to-be-scanned filesystem. 
        optional: false
        mountPath: /$(params.fs-scan)
  
  steps:
    - name: scan-fs-step
      image: aquasec/trivy:0.16.0
      workingDir: /$(params.fs-scan)
      script:  |
        
        pip freeze > requirements.txt
        pipenv lock
        trivy fs .



      
      
           

        
