apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: scan-pipeline-fs
spec:
  params:
    - name: fs-scan

    
  tasks:
      
  - name: scan-fs
    
    taskRef:
      name: scan-fs
   
    params:
      - name: fs-scan
        value: $(params.fs-scan)
    


  
  
   
      
