apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: scan-pipeline-fs
spec:
  params:
    - name: fs-scan
  workspaces:
  - name: workspace
    
  tasks:
      
  - name: scan-fs
    
    taskRef:
      name: scan-fs
    workspaces:
      - name: source
        workspace: workspace
    params:
      - name: fs-scan
        value: $(params.fs-scan)
    


  
  
   
      
