apiVersion: tekton.dev/v1beta1

kind: Task

metadata:
  name: scan-fs

spec:
  description: This task is for scanning the file system.
  
  params:
    - name: fs-scan
      type: string
      description: Absolute path of the filesystem to be scanned.
      default: ""

  workspaces:
    - name: input
      description: Workspace for storing to-be-scanned filesystem. 
      mountPath: /workspace/input/$(params.fs-scan)
  
  steps:
    - name: scan-fs-step
      image: aquasec/trivy:0.16.0
      workingDir: /workspace/input/$(params.fs-scan)
      script:  |
        
        pip freeze > requirements.txt
        pipenv lock
        trivy fs .



      
      
           

        
