apiVersion: tekton.dev/v1beta1

kind: Task

metadata:
  name: scan-fs

spec:
  description: This task is for scanning the file system.

  workspaces:
    - name: workspace
      description: Workspace for fetched image.

  params:
    - name: path-scan
      type: string
      description: Absolute path of the filesystem to be scanned.
      default: ""

  steps:
    - name: scan-image-step
      image: aquasec/trivy:0.16.0
      workingDir: $(workspaces.source.path)
      script:  |
        cd ~
        cd $(params.path-scan)
        pip freeze > requirements.txt
        pipenv lock
        trivy fs .
    
